config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  resources :companies
  resources :countries
  resources :states
  resources :cities
  resources :places
  resources :nodes
  resources :regions
  resources :roles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

	mount_uploader :city_image, CityUploader
	  has_many :companies
      
  belongs_to :state

  validates :city_name, presence: true,
                    length: { minimum: 3 }
     validates :city_name, uniqueness: true

end

app/models/company.rb
class Company < ApplicationRecord

	  mount_uploader :company_image, CompanyUploader
  belongs_to :country
  belongs_to :state
  belongs_to :city
  has_many :places
  has_many :nodes
  has_many :users
  # validates :name, presence: true,
  #                   length: { minimum: 3 }
  #    validates :name, uniqueness: true

end

app/models/country.rb
class Country < ApplicationRecord
	mount_uploader :country_image, CountryUploader
	  has_many :states
	  has_many :cities
	  has_many :companies
	  has_many :places
	  has_many :nodes

	 validates :country_name, presence: true,
                    length: { minimum: 3 }
     validates :country_name, uniqueness: true

end

app/models/node.rb
class Node < ApplicationRecord
	belongs_to :place

	validates :node_name, presence: true,
                    length: { minimum: 3 }
     validates :node_name, uniqueness: true

end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :company
  has_many :nodes
  validates :place_name, presence: true,
                    length: { minimum: 3 }
     validates :place_name, uniqueness: true

end

app/models/region.rb
class Region < ApplicationRecord
	validates :region_name, presence: true,
                    length: { minimum: 3 }
     validates :region_name, uniqueness: true

end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
mount_uploader :state_image, StateUploader

  belongs_to :country
  has_many :cities
  has_many :companies
  has_many :places
  has_many :nodes
  
validates :state, presence: true,
                    length: { minimum: 3 }
     validates :state, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
 belongs_to :company
 belongs_to :role
	mount_uploader :image, UserUploader


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	
  def  show
  	@company=Company.find(params[:id])
  end

  def create
    @company = Company.new(company_params)
     
      if @company.save
        redirect_to @company
      else
        render 'new'
      end
  end

  

  def new
  	@company=Company.new
  end


  private
    def company_params
      params.require(:company).permit( :name, :company_image, :country_id, :country_name, :state_id, :state, :city_id, :city_name, :postcode, :start_date, :active)
    end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
	def  show
  	@node=Node.find(params[:id])
  end

  def create
    @node = Node.new(node_params)
     
      if @node.save
        redirect_to @node
      else
        render 'new'
      end
  end

  

  def new
  	@node=Node.new
  end

 

  
 
  private
    def node_params
      params.require(:node).permit(:node_name,  :place_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
 
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@company.errors.count, "error") %> prohibited
        this company from being saved:
      </h2>
      <ul>
        <% @company.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <p>
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
  </p>
 

<p>
    <%= f.label :select_country %><br>
    <%= f.collection_select :country_id, Country.order(:country_name),:id,:country_name, include_blank: true %>
  </p>


 <p>
    <%= f.label :select_state %><br>
    <%= f.collection_select :state_id, State.order(:state),:id,:state, include_blank: true %>
  </p>

 <p>
    <%= f.label :select_city %><br>
    <%= f.collection_select :city_id, City.order(:city_name),:id,:city_name, include_blank: true %>
  </p>

   <p>
    <%= f.label :start_date %><br>
    <%= f.date_field :start_date %>
  </p>
 


<p>
    <%= f.label :postcode %><br>
    <%= f.number_field :postcode %>
  </p>
<p>
    <%= f.label :company_image %><br>
    <%= f.file_field :company_image %>
  </p>


  
 
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/companies/new.html.erb
<h1> Company </h1>
<%= render 'form' %>

app/views/companies/show.html.erb
<p>
  <strong>country name:</strong>
  <%= @company.city.state.country.country_name %>
</p>

<p>
  <strong>state name:</strong>
  <%= @company.city.state.state %>
</p>

<p>
  <strong>city name:</strong>
  <%= @company.city.city_name %>
</p>


<p>
  <strong>company name:</strong>
  <%= @company.name %>
</p>


<%= image_tag(@company.company_image.url, size:10*10) %></br>
 
 <%= link_to 'Next page', new_place_path %> |


<%= link_to 'Back to New city', new_city_path %>     
 