config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  resources :companies
  resources :countries
  resources :states
  resources :cities
  resources :places
  resources :nodes
  resources :regions
  resources :roles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

	mount_uploader :city_image, CityUploader
	  has_many :companies
      
  belongs_to :state

  validates :city_name, presence: true,
                    length: { minimum: 3 }
     validates :city_name, uniqueness: true

end

app/models/company.rb
class Company < ApplicationRecord

	  mount_uploader :company_image, CompanyUploader
  belongs_to :country
  belongs_to :state
  belongs_to :city
  has_many :places
  has_many :nodes
  has_many :users
  # validates :name, presence: true,
  #                   length: { minimum: 3 }
  #    validates :name, uniqueness: true

end

app/models/country.rb
class Country < ApplicationRecord
	mount_uploader :country_image, CountryUploader
	  has_many :states
	  has_many :cities
	  has_many :companies
	  has_many :places
	  has_many :nodes

	 validates :country_name, presence: true,
                    length: { minimum: 3 }
     validates :country_name, uniqueness: true

end

app/models/node.rb
class Node < ApplicationRecord
	belongs_to :place

	validates :node_name, presence: true,
                    length: { minimum: 3 }
     validates :node_name, uniqueness: true

end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :company
  has_many :nodes
  validates :place_name, presence: true,
                    length: { minimum: 3 }
     validates :place_name, uniqueness: true

end

app/models/region.rb
class Region < ApplicationRecord
	validates :region_name, presence: true,
                    length: { minimum: 3 }
     validates :region_name, uniqueness: true

end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
mount_uploader :state_image, StateUploader

  belongs_to :country
  has_many :cities
  has_many :companies
  has_many :places
  has_many :nodes
  
validates :state, presence: true,
                    length: { minimum: 3 }
     validates :state, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
 belongs_to :company
 belongs_to :role
	mount_uploader :image, UserUploader


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  def index
    @countries = Country.all
  end

	def show
    @country = Country.find(params[:id])
  end

	def new
    @country = Country.new
  end

  def edit
  @country = Country.find(params[:id])
  end


  def create

      @country = Country.new(country_params)
   	 
      if @country.save
        redirect_to @country
      else
        render 'new'
      end
  end

  def update
  @country = Country.find(params[:id])
 
  if @country.update(country_params)
    redirect_to @country
  else
    render 'edit'
  end
  end

  def destroy
  @country = Country.find(params[:id])
  @country.destroy
 
  redirect_to countries_path
  end
 

	private
	  def country_params
	    params.require(:country).permit(:country_name, :country_image)
	  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
	def  show
  	@node=Node.find(params[:id])
  end

  def create
    @node = Node.new(node_params)
     
      if @node.save
        redirect_to @node
      else
        render 'new'
      end
  end

  

  def new
  	@node=Node.new
  end

 

  
 
  private
    def node_params
      params.require(:node).permit(:node_name,  :place_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/countries/_form.html.erb
<%= form_for @country do |f| %>
 
  <% if @country.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@country.errors.count, "error") %> prohibited
        this country from being saved:
      </h2>
      <ul>
        <% @country.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= f.label :country_name %><br>
    <%= f.text_field :country_name %><p>
    
  </p>
<p>
    <%= f.label :country_image %><br>
    <%= f.file_field :country_image %>
  </p>

  </p>
 
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/countries/edit.html.erb
<h1>Editing country</h1>
 
<%= render 'form' %>

 
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<h1>Listing countries</h1>
<%= link_to 'New country', new_country_path %>
 
<table>
  <tr>
    <th>Country name</th>
    
  </tr>
 
  <% @countries.each do |country| %>
    <tr>
      <td><%= country.country_name %></td>
      <td><%= link_to 'Show', country_path(country) %></td>
      <td><%= link_to 'Edit', edit_country_path(country) %></td>
       <td><%= link_to 'Destroy', country_path(country),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/countries/new.html.erb
<h1>New counrty</h1>
<%= render 'form' %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<p>
  <strong>Country name:</strong>
  <%= @country.country_name %>
</p>

 
<%= image_tag(@country.country_image.url, size:10*10) %></br>


<%= link_to 'Next page', new_state_path %> |

<%= link_to 'Edit', edit_country_path(@country) %> |

 
<%= link_to 'Back', countries_path %>