config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  resources :companies
  resources :countries
  resources :states
  resources :cities
  resources :places
  resources :nodes
  resources :regions
  resources :roles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

	mount_uploader :city_image, CityUploader
	  has_many :companies
      
  belongs_to :state

  validates :city_name, presence: true,
                    length: { minimum: 3 }
     validates :city_name, uniqueness: true

end

app/models/company.rb
class Company < ApplicationRecord

	  mount_uploader :company_image, CompanyUploader
  belongs_to :country
  belongs_to :state
  belongs_to :city
  has_many :places
  has_many :nodes
  has_many :users
  # validates :name, presence: true,
  #                   length: { minimum: 3 }
  #    validates :name, uniqueness: true

end

app/models/country.rb
class Country < ApplicationRecord
	mount_uploader :country_image, CountryUploader
	  has_many :states
	  has_many :cities
	  has_many :companies
	  has_many :places
	  has_many :nodes

	 validates :country_name, presence: true,
                    length: { minimum: 3 }
     validates :country_name, uniqueness: true

end

app/models/node.rb
class Node < ApplicationRecord
	belongs_to :place

	validates :node_name, presence: true,
                    length: { minimum: 3 }
     validates :node_name, uniqueness: true

end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :company
  has_many :nodes
  validates :place_name, presence: true,
                    length: { minimum: 3 }
     validates :place_name, uniqueness: true

end

app/models/region.rb
class Region < ApplicationRecord
	validates :region_name, presence: true,
                    length: { minimum: 3 }
     validates :region_name, uniqueness: true

end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
mount_uploader :state_image, StateUploader

  belongs_to :country
  has_many :cities
  has_many :companies
  has_many :places
  has_many :nodes
  
validates :state, presence: true,
                    length: { minimum: 3 }
     validates :state, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
 belongs_to :company
 belongs_to :role
	mount_uploader :image, UserUploader


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
	


  def  show
  	@city=City.find(params[:id])
  end

  def create
    @city = City.new(city_params)
     
      if @city.save
        redirect_to @city
      else
        render 'new'
      end
  end

  

  def new
  	@city=City.new
  end

 

  
 
  private
    def city_params
      params.require(:city).permit(:city_name, :state_id, :city_image)
    end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
	def  show
  	@node=Node.find(params[:id])
  end

  def create
    @node = Node.new(node_params)
     
      if @node.save
        redirect_to @node
      else
        render 'new'
      end
  end

  

  def new
  	@node=Node.new
  end

 

  
 
  private
    def node_params
      params.require(:node).permit(:node_name,  :place_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cities/_form.html.erb
<%= form_for @city do |f| %>
 
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@city.errors.count, "error") %> prohibited
        this city from being saved:
      </h2>
      <ul>
        <% @city.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    

 <p>
    <%= f.label :select_state %><br>
    <%= f.collection_select :state_id, State.order(:state),:id,:state, include_blank: true %>
  </p>

  <p>
    <%= f.label :city_name %><br>
    <%= f.text_field :city_name %>
  </p>
  
  <p>
    <%= f.label :city_image %><br>
    <%= f.file_field :city_image %>
  </p>

 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/cities/new.html.erb
<h1>New city</h1>
<%= render 'form' %>

app/views/cities/show.html.erb
<p>
  <strong>country name:</strong>
  <%= @city.state.country.country_name %>
</p>

<p>
  <strong>state name:</strong>
  <%= @city.state.state %>
</p>

<p>
  <strong>city name:</strong>
  <%= @city.city_name %>
</p>

<%= image_tag(@city.city_image.url, size:10*10) %></br>


  <p>
    <%= f.label :city_image %><br>
    <%= f.file_field :city_image %>
  </p>


<%= link_to 'Next page', new_company_path %> |


<%= link_to 'Back to New city', new_city_path %>     
 